## Chapter 6. 엑셀보다 판다스

### 6.1

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

np.random.seed(85)
data = np.random.randint(0, 100, size=5)
num_series = pd.Series(data, index = ['a','b','c','d','e'])
num_series

a    32
b    13
c    68
d    51
e    13
dtype: int64

#### 1)

In [3]:
print(f"num_series의 최대값: {max(num_series)}")

num_series의 최대값: 68

#### 2)

In [5]:
print(f"num_series의 최소값: {min(num_series)}")

num_series의 최소값: 13

#### 3)

In [7]:
print(f"num_series의 평균값: {np.mean(num_series)}")

num_series의 평균값: 35.4

### 6.2

#### 1)

In [11]:
path = 'https://github.com/dongupak/DataML/raw/main/csv/'
weather_file = path + 'weather.csv'

weather = pd.read_csv(weather_file, index_col = 0, encoding='CP949')
print(f"{weather.head(3)}\n\n{weather.tail(3)}\n")

            평균기온  최대풍속  평균풍속
일시
2010-08-01  28.7   8.3   3.4
2010-08-02  25.2   8.7   3.8
2010-08-03  22.1   6.3   2.9

            평균기온  최대풍속  평균풍속
일시
2020-07-29  21.6   3.2   1.0
2020-07-30  22.9   9.7   2.4
2020-07-31  25.7   4.8   2.5

#### 2)

In [12]:
print(f"{weather.loc['2015-06-06']}")

평균기온    16.6
최대풍속     4.4
평균풍속     1.9
Name: 2015-06-06, dtype: float64

#### 3)

In [14]:
print(f"{weather[weather['평균기온']==weather['평균기온'].max()]}")

            평균기온  최대풍속  평균풍속
일시
2013-08-08  31.3   7.8   4.6

#### 4)

In [16]:
print(f"{weather[weather['평균기온'] >= 30]}")

            평균기온  최대풍속  평균풍속
일시
2013-08-08  31.3   7.8   4.6
2013-08-09  30.6   9.9   6.4
2013-08-10  30.6   7.4   3.8
2018-07-23  30.5   6.5   1.6
2018-08-04  30.3   5.8   3.0

### 6.3

In [19]:
df_1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index = ['0', '1', '2'])

df_2 = pd.DataFrame({
    'B': ['B2', 'B3'],
    'C': ['C2', 'C3'],
    'D': ['D2', 'D3'],
    'E': ['E2', 'E3']
}, index = ['0', '1'])

print(f"{df_1}\n\n{df_2}\n")

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

    B   C   D   E
0  B2  C2  D2  E2
1  B3  C3  D3  E3

#### 1)

In [20]:
df_3 = pd.concat([df_1, df_2])
print(df_3)

     A   B   C   D    E
0   A0  B0  C0  D0  NaN
1   A1  B1  C1  D1  NaN
2   A2  B2  C2  D2  NaN
0  NaN  B2  C2  D2   E2
1  NaN  B3  C3  D3   E3

#### 2)

In [27]:
df_4 = pd.concat([df_1, df_2], axis=1, join='inner')
print(df_4)

    A   B   C   D   B   C   D   E
0  A0  B0  C0  D0  B2  C2  D2  E2
1  A1  B1  C1  D1  B3  C3  D3  E3

### 6.4

In [119]:
path = 'http://github.com/dongupak/DataML/raw/main/csv/'
file = path + 'trade_month.csv'
trade = pd.read_csv(file, encoding='cp949')

#### 1)

In [120]:
trade.head(5)

        기간  국가명     수출건수        수출금액     수입건수       수입금액        무역수지
0  2015.01   중국  116,932  12,083,947  334,522  8,143,271   3,940,676
1  2015.01   미국   65,888   5,561,545  509,564  3,625,062   1,936,484
2  2015.01   일본   54,017   2,251,307   82,480  3,827,247  -1,575,940
3  2015.01   홍콩   31,348   2,170,483   12,595    175,487   1,994,996
4  2015.01  베트남   38,008   2,163,836   15,720    704,086   1,459,749

#### 2)

In [121]:
trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2750 entries, 0 to 2749
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기간      2750 non-null   float64
 1   국가명     2750 non-null   object
 2   수출건수    2750 non-null   object
 3   수출금액    2749 non-null   object
 4   수입건수    2750 non-null   object
 5   수입금액    2750 non-null   object
 6   무역수지    2749 non-null   object
dtypes: float64(1), object(6)
memory usage: 150.5+ KB

#### 3)

In [122]:
trade['기간'] = trade['기간'].astype(str)

for x in list(trade.columns[2:]):
    trade[x] = trade[x].str.replace(',','').astype(float)

trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2750 entries, 0 to 2749
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   기간      2750 non-null   object
 1   국가명     2750 non-null   object
 2   수출건수    2750 non-null   float64
 3   수출금액    2749 non-null   float64
 4   수입건수    2750 non-null   float64
 5   수입금액    2750 non-null   float64
 6   무역수지    2749 non-null   float64
dtypes: float64(5), object(2)
memory usage: 150.5+ KB

#### 4)

In [123]:
print(trade.isnull().sum)

<bound method DataFrame.sum of          기간    국가명   수출건수   수출금액   수입건수   수입금액   무역수지
0     False  False  False  False  False  False  False
1     False  False  False  False  False  False  False
2     False  False  False  False  False  False  False
3     False  False  False  False  False  False  False
4     False  False  False  False  False  False  False
...     ...    ...    ...    ...    ...    ...    ...
2745  False  False  False  False  False  False  False
2746  False  False  False  False  False  False  False
2747  False  False  False  False  False  False  False
2748  False  False  False  False  False  False  False
2749  False  False  False  False  False  False  False

[2750 rows x 7 columns]>

#### 5)

In [124]:
trade[trade.isnull().any(axis=1)]

           기간    국가명    수출건수  수출금액    수입건수     수입금액  무역수지
1189  2015.06  체코공화국  2115.0   NaN  1804.0  46722.0   NaN

#### 6)

In [125]:
trade567 = trade[(trade['국가명']=='체코공화국') & (trade['기간']>='2015.05') & (trade['기간']<='2015.07') & (trade['기간']!='2015.06')]

trade.loc[1189, '수출금액'] = trade567['수출금액'].mean()
trade.loc[1189, '무역수지'] = trade567['무역수지'].mean()

trade.loc[[1189]]

           기간    국가명    수출건수      수출금액    수입건수     수입금액      무역수지
1189  2015.06  체코공화국  2115.0  215563.5  1804.0  46722.0  164045.0

#### 7)

In [126]:
display(trade[trade.duplicated()])
display(trade[(trade['기간']=='2015.02')&(trade['국가명']=='중국')])
trade.drop_duplicates(inplace=True)
display(trade[trade.duplicated()])

          기간 국가명     수출건수       수출금액      수입건수       수입금액       무역수지
230  2015.02  중국  86228.0  9927642.0  209100.0  6980874.0  2946768.0

          기간 국가명     수출건수       수출금액      수입건수       수입금액       무역수지
229  2015.02  중국  86228.0  9927642.0  209100.0  6980874.0  2946768.0
230  2015.02  중국  86228.0  9927642.0  209100.0  6980874.0  2946768.0

Empty DataFrame
Columns: [기간, 국가명, 수출건수, 수출금액, 수입건수, 수입금액, 무역수지]
Index: []